apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: simple-app
  template:
    metadata:
      labels:
        app: simple-app
    spec:
      containers:
        - name: simple-app
          image: danchiwaz/simple-app
          ports:
            - containerPort: 5000
          startupProbe:
            httpGet:
              port: 5000
              path: /health
            failureThreshold: 6 #allows up to 60s (6*10s) for startup
            periodSeconds: 10
          readinessProbe:
            httpGet:
              port: 5000
              path: /health
            initialDelaySeconds: 3
            periodSeconds: 5
            failureThreshold: 2
          livenessProbe:
            httpGet:
              port: 5000
              path: /health
            initialDelaySeconds: 35
            periodSeconds: 10
            failureThreshold: 3

