apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replicaset
spec:
  template:
    metadata:
      name: my-replicaset
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
        - name: nginx-controller
          image: nginx
  replicas: 3
  selector:
    matchLabels:
      type: front-end